# Generated by Django 4.2.3 on 2023-07-18 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_user_is_client_user_is_volunteer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'Finding Volunteers'), ('2', 'Working'), ('3', 'Final Touches'), ('4', 'Completed')], default='1', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product_link', models.URLField(blank=True, null=True)),
                ('github_link', models.URLField(blank=True, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('developers', models.ManyToManyField(related_name='projects_developed', to='accounts.volunteer')),
                ('managers', models.ManyToManyField(related_name='projects_managed', to='accounts.volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('task_description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('assign', models.ManyToManyField(related_name='tasks_assigned', to='accounts.volunteer')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'ordering': ['project', 'task_name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_business', models.BooleanField()),
                ('slug', models.SlugField(unique=True)),
                ('status', models.CharField(choices=[('1', 'Pending'), ('2', 'Verified'), ('3', 'Rejected')], default='1', max_length=100)),
                ('business', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='accounts.business')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='accounts.client')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='project_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='projects.projectrequest'),
        ),
    ]
