# Generated by Django 4.2.3 on 2023-07-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projectrequest_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='is_business',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='slug',
            field=models.SlugField(),
        ),
    ]
