# Generated by Django 4.2.3 on 2023-07-19 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_business_user'),
        ('projects', '0003_alter_project_slug_alter_projectrequest_is_business_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrequest',
            name='business',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='accounts.business'),
        ),
    ]
