# Generated by Django 4.2.3 on 2023-07-21 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_volunteer_volunteer_hours"),
        ("projects", "0005_volunteerlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volunteerlog",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="volunteerlog",
            name="volunteer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="accounts.volunteer",
            ),
        ),
    ]
