# Generated by Django 4.2.3 on 2023-07-21 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_alter_volunteerlog_date_alter_volunteerlog_volunteer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("1", "Pending Verification"),
                    ("2", "Verified"),
                    ("3", "Rejected"),
                ],
                default="1",
                max_length=100,
            ),
        ),
    ]
