# Generated by Django 4.2.3 on 2023-07-21 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_business_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="volunteer",
            name="volunteer_hours",
        ),
    ]
