# Generated by Django 4.2.3 on 2023-07-21 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_volunteer_volunteer_hours"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="img",
            field=models.ImageField(
                default="accounts/blank_profile.png", upload_to="avatars"
            ),
        ),
    ]
