# Generated by Django 4.2.3 on 2023-07-22 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_user_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="img",
            field=models.ImageField(
                default="avatars/blank_profile.png", upload_to="avatars"
            ),
        ),
    ]
